name: rtb-bidder
version: '0.1.0.0'
synopsis: An implementation for Real-time bidding containing OpenRTB
category: Web
author: Masahiro Honma
maintainer: hiratara@cpan.org
license: BSD3
dependencies:
- bytestring
- protocol-buffers
library:
  source-dirs: src/
  dependencies:
  - base >=4.7 && <4.10
  - http-types
  - wai
  - text
  - aeson
  - containers
tests:
  test-rtb-bidder:
    main: test-rtb-bidder.hs
    source-dirs: test/
    dependencies:
    - rtb-bidder
    - base
    - wai-extra
